# Generated by Django 5.2.7 on 2025-10-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
    ]
