# Generated by Django 5.2.7 on 2025-11-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_money',
        ),
    ]
